"""empty message

Revision ID: 47de1903b00
Revises: 15c488d628b
Create Date: 2015-10-01 13:29:56.074228

"""

# revision identifiers, used by Alembic.
revision = '47de1903b00'
down_revision = '15c488d628b'

# add this here in order to use revision with branch_label
branch_labels = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('objects', 'title')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('objects', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    ### end Alembic commands ###
