= Beavy


image:https://img.shields.io/travis/beavyHQ/beavy.svg?style=flat-square[link="https://travis-ci.org/beavyHQ/beavy"] image:https://img.shields.io/codeclimate/github/beavyHQ/beavy.svg?style=flat-square[link="https://codeclimate.com/github/beavyHQ/beavy"] image:https://img.shields.io/coveralls/beavyHQ/beavy.svg?style=flat-square[link="https://coveralls.io/github/beavyHQ/beavy?branch=master"] image:https://img.shields.io/badge/waffle-Contribute-4078c0.svg?style=flat-square[link="https://waffle.io/beavyHQ/beavy"] image:https://img.shields.io/badge/gitter-Chat-ff69b4.svg?style=flat-square[link="https://gitter.im/beavyHQ/beavy?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge"]  image:https://img.shields.io/badge/twitter-Follow-8E5990.svg?style=flat-square[link="https://www.twitter.com/beavyHQ]

**Main Repo**: https://github.com/beavyHQ/beavy

Beavy is a modular, multi-purpose social community building framework. This is its main source development repository.

Please see the link:http://beavy.xyz/[Website] and the link:https://beavyhq.gitbooks.io/beavy-documentation/content/[Development Documentation] (as link:https://www.gitbook.com/download/pdf/book/beavyhq/beavy-documentation[PDF], link:https://www.gitbook.com/download/epub/book/beavyhq/beavy-documentation[epub] or link:https://www.gitbook.com/download/mobi/book/beavyhq/beavy-documentation[mobi]) to learn more about the project.

image:http://beavy.xyz/logos/logo.svg[Beavy Logo]

== Code of Conduct

image:https://img.shields.io/badge/Code_of_Conduct-Contributor_Covenant-green.svg?style=flat-square[link="http://contributor-covenant.org/"]

This project is managed under an adapted link:http://contributor-covenant.org/[Contributer Convenant] Code of Conduct, applicable to everyone involved in the project (including core committers, maintainers and sponsors) in all forms of online and offline communication (public and private) as well as for all affiliated events and meetings.

link:./CODE_OF_CONDUCT.adoc[Read the full Code of Conduct here].


== License
This Project is licensed under the Mozilla Public License, v. 2.0. You can find the full license text in the LICENSE file in the main directory or at http://mozilla.org/MPL/2.0/ .
