"""empty message

Revision ID: 33e616d4d32
Revises: 4df60c86756
Create Date: 2015-09-10 22:51:03.319780

"""

# revision identifiers, used by Alembic.
revision = '33e616d4d32'
down_revision = '4df60c86756'

from alembic import op
import sqlalchemy as sa

import datetime


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True, default=datetime.datetime.now),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('like')
    ### end Alembic commands ###
