"""empty message

Revision ID: 3a2d790251f
Revises: 2bbba89c769
Create Date: 2015-09-11 19:22:56.579058

"""

# revision identifiers, used by Alembic.
revision = '3a2d790251f'
down_revision = '2bbba89c769'
depends_on = "44f6d7926bf"

# add this here in order to use revision with branch_label
branch_labels = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('like')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('like',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='like_pkey')
    )
    ### end Alembic commands ###
