"""empty message

Revision ID: 3e068a6cf46
Revises: 1d461753b2e
Create Date: 2015-09-17 18:20:12.465046

"""

# revision identifiers, used by Alembic.
revision = '3e068a6cf46'
down_revision = None
depends_on = '1d461753b2e'

# add this here in order to use revision with branch_label
branch_labels = ('beavy.likes', )

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('objects', sa.Column('likes_count', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('objects', 'likes_count')
    ### end Alembic commands ###
