"""empty message

Revision ID: 242c2fd98af
Revises: 3e4bfaac605
Create Date: 2015-09-11 11:41:02.655056

"""

# revision identifiers, used by Alembic.
revision = '242c2fd98af'
down_revision = '3e4bfaac605'

# add this here in order to use revision with branch_label
branch_labels = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import datetime

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('objects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True,  default=datetime.datetime.now),
    sa.Column('payload', postgresql.JSONB(), nullable=True),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.Column('belongs_to', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['belongs_to'], ['objects.id'], ),
    sa.ForeignKeyConstraint(['owner'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('objects')
    ### end Alembic commands ###
