"""empty message

Revision ID: 3e4bfaac605
Revises: 33e616d4d32
Create Date: 2015-09-10 22:54:15.098614

"""

# revision identifiers, used by Alembic.
revision = '3e4bfaac605'
down_revision = '4df60c86756'

from alembic import op
import sqlalchemy as sa

branch_labels = ('beavy', )

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'name')
    ### end Alembic commands ###
