"""empty message

Revision ID: 44f6d7926bf
Revises: 242c2fd98af
Create Date: 2015-09-11 15:04:06.913899

"""

# revision identifiers, used by Alembic.
revision = '44f6d7926bf'
down_revision = '242c2fd98af'

# add this here in order to use revision with branch_label
branch_labels = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.Integer(), nullable=True),
    sa.Column('verb', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('object', sa.Integer(), nullable=True),
    sa.Column('whom', sa.Integer(), nullable=True),
    sa.Column('payload', postgresql.JSONB(), nullable=True),
    sa.ForeignKeyConstraint(['object'], ['objects.id'], ),
    sa.ForeignKeyConstraint(['subject'], ['user.id'], ),
    sa.ForeignKeyConstraint(['whom'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activities')
    ### end Alembic commands ###
