
export const STORY_SUBMIT = 'STORY_SUBMIT'

export const STORY_SUBMIT_REQUEST = STORY_SUBMIT + '_REQUEST'
export const STORY_SUBMIT_SUCCESS = STORY_SUBMIT + '_SUCCESS'
export const STORY_SUBMIT_FAILURE = STORY_SUBMIT + '_FAILURE'
